# Generated by Django 2.2.11 on 2020-05-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0054_add_create_reminder_delete_reminder_and_review_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='visible_to_applicants',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='visible_to_partners',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='visible_to_reviewers',
            field=models.BooleanField(default=False),
        ),
    ]
